# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to='private/', width_field='width')),
                ('covered_image', models.ImageField(height_field='height', upload_to='public/', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True)),
                ('height', models.PositiveIntegerField(blank=True)),
                ('uncovered', models.TextField(blank=True)),
            ],
        ),
    ]
