# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import picture.models
import picturepay.storage


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='picture',
            name='covered_image',
            field=models.ImageField(blank=True, storage=picturepay.storage.OverwriteStorage(), upload_to=picture.models.covered_picture_path),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(height_field='height', upload_to=picture.models.picture_path, width_field='width'),
        ),
    ]
