# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_paymentnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentnote',
            name='type',
        ),
    ]
