# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_remove_paymentnote_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentnote',
            old_name='url',
            new_name='name',
        ),
        migrations.AddField(
            model_name='paymentnote',
            name='picture',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='note', to='picture.Picture'),
            preserve_default=False,
        ),
    ]
