# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0007_auto_20161013_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentnote',
            old_name='message',
            new_name='url',
        ),
    ]
