# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0008_auto_20161013_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='paymentnote',
            name='pixels',
            field=models.ManyToManyField(related_name='notes', to='picture.Pixel'),
        ),
    ]
