# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0009_auto_20161015_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='b',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixel',
            name='g',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pixel',
            name='r',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
