# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0010_auto_20161015_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnote',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentnote',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
